apiVersion: v1
kind: ServiceAccount
metadata:
  name: getup-controller
  namespace: getup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: getup-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: getup-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: getup-controller
subjects:
- kind: ServiceAccount
  name: getup-controller
  namespace: getup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getup-controller
  namespace: getup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getup-controller
  template:
    metadata:
      labels:
        app: getup-controller
    spec:
      containers:
      - name: controller
        env:
        - name: GETUP_API_URL
          value: "http://api.getup.svc:8080"
        - name: GETUP_API_USERNAME
          value: ""
        - name: GETUP_API_PASSWORD
          value: ""
        image: getupcloud/getup-controller:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: getup-controller

