resources:
- group: ""
  version: v1
  kind: Namespace
  reconciler:
    exec:
      command: /app/project-reconciler.py
      debug: false
    observe: true
  validator:
    exec:
      command: /app/project-validator.py
